# Generated by Django 2.0 on 2017-12-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=10)),
                ('available', models.BooleanField(default=1)),
                ('status', models.IntegerField(default=1)),
                ('user', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('age', models.IntegerField()),
                ('password', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('permission', models.IntegerField(default=3)),
            ],
        ),
    ]
