# Generated by Django 2.0 on 2018-01-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='img',
            field=models.ImageField(default='img/l2.jpg', upload_to='./static/upload'),
        ),
    ]
