# Generated by Django 2.0 on 2018-01-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_room_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='evaluation',
            field=models.CharField(default='暫無評價', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='fraction',
            field=models.CharField(default='star2.png', max_length=10),
        ),
    ]
