# Generated by Django 2.0 on 2018-01-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_room_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Latest_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=500)),
                ('img', models.ImageField(upload_to='./static/upload/')),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='img',
            field=models.ImageField(default='img/l2.jpg', upload_to='./static/upload/'),
        ),
    ]
