# Generated by Django 2.0 on 2018-01-10 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel_environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('img', models.ImageField(upload_to='./static/upload/')),
                ('content', models.CharField(max_length=100)),
            ],
        ),
    ]
